checks:
  php: true

filter:
  paths:
    - "src/*"

tools:
  external_code_coverage: true

build:
  nodes:
    analysis:
      environment:
        php: 7.4.14

      tests:
        override:
          - php-scrutinizer-run
