name: build

on:
  pull_request:
    paths: &paths
      - '.github/workflows/build.yml'
      - 'src/**'
      - 'tests/**'
      - 'composer.json'
      - 'phpunit.xml.dist'
  push:
    branches: [ 'master' ]
    paths: *paths

permissions:
  contents: read

jobs:
  tests:
    name: PHP ${{ matrix.php }}-${{ matrix.os }}

    env:
      extensions: pdo, pdo_oci, oci8
      key: cache-v1

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest

        php:
          - 7.4
          - 8.0
          - 8.1

    services:
      oci:
        image: wnameless/oracle-xe-11g-r2@sha256:e8cfa3733a2c11b415fb94a9632424025d69165fb4903a22206f6073be30eeb9
        ports:
          - 1521:1521
        options: --name=oci

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Install PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          php-version: ${{ matrix.php }}
          extensions: ${{ env.extensions }}
          ini-values: date.timezone='UTC'
          coverage: pcov
          tools: composer:v2

      - name: Install Composer dependencies
        uses: ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda # 4.0.0

      - name: Run tests with phpunit and coverage
        run: vendor/bin/phpunit --coverage-clover=coverage.clover --colors=always

      - name: Upload code coverage scrutinizer
        continue-on-error: true
        run: |
          wget https://scrutinizer-ci.com/ocular.phar
          php ocular.phar code-coverage:upload --format=php-clover coverage.clover
